### PR TITLE
Initial version of proposal for consumer standardization

### PR DESCRIPTION
**Pull request by markborkum**
### Description

Proposal to standardize the behavior of consumers of CloudEvents notifications (corresponding to Pacifica transactions).

### Issues Resolved

n/a

### Check List

- [ ] All tests pass. See <https://github.com/pacifica/pacifica-docs/blob/master/development/TESTING.md>
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable

### CODE REVIEW

**Comment by dmlb2000** [comment]
@markborkum I think this is fine, but we could put a little different spin on it. Can you move the document to `docs/consumer-expectations.md` and drop the proposal/justifications sections at the top. Just go right into what it takes to build a consumer of this service.

Thanks, good work too!

**Comment by dmlb2000** [comment]
In the section `Open Questions` the title suggests you are going to address these questions, should that part in the parens just go away? Or are you going to add more info for solving those questions?

**Comment by markborkum** [comment]
@dmlb2000 I'm going to add more information. We should try to address as many "open questions" as possible before starting the software development. The most pertinent are: authentication/authorization, blocking on multiple notifications, and persistence of locally-generated files.

**Comment by dmlb2000** [comment]
@markborkum Is this ready to merge?

**Comment by markborkum** [comment]
@dmlb2000 Not quite yet. @khm and I are debating whether or not to use callbacks/continuations for the downloader and uploader (instead of having them be invoked automatically on either side of the consumer's invocation).

**Comment by khm** [comment]
Excuse my ignorance:  does the introduction of promises tie us to a python implementation for consumers?

**Comment by markborkum** [comment]
@khm In principal, no. 

There are two scenarios:
1. Invoking non-Python userspace code from a Python entry-point.
2. Invoking non-Python userspace code from a non-Python entry-point.

For (1), the entry-point is still responsible for downloading/uploading files before/after the non-Python userspace code is invoked.

For (2), if we were to develop "wrapper" packages for other programming languages, then implementations of the Promises/A+ spec are widely available (see https://promisesaplus.com/implementations for listing).

**Comment by dmlb2000** [comment]
@markborkum I didn't notice this last time, you mention installing the pacifica-notifications-consumer package. Should I setup a new repository and pipeline for that so it can be hosted here? Or is that package somewhere else that I'm not seeing?

**Comment by markborkum** [comment]
@dmlb2000 The `pacifica-notifications-consumer` package is to be developed. This proposal is its requirements/specification document.

No need for a new repository at this point, thanks.

**Comment by dmlb2000** [comment]
@markborkum So just to verify since we've moved a bit on this ticket... We've got `pacifica-dispatcher` library and a `pacifica-dispatcher-proxymod` example but not yet the `pacifica-dispatcher-example`. Is this going to wait for `pacifica-dispatcher-example` or can this be updated to `pacifica-dispatcher` and merged?

Thoughts?

**Comment by markborkum** [comment]
@dmlb2000, I will push to `pacifica-dispatcher-example` very soon. It will [eventually] contain a barebones "Hello, world!" dispatcher implementation that lists `pacifica-dispatcher` in `requirements.txt`. Please do not merge the repositories.

**Pull request merged**
